description: "A mobile-based application that calculates the Body Mass Index (BMI) of a person."
name: bmi

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/weighing-machine.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash-weighing-machine.png
  android_12:
    image: assets/splash-weighing-machine.png
    icon_background_color: "#ffffff"
    fullscreen: true